# ================================================
# Workflow de GitHub Actions para desplegar Node.js
# en Azure App Service (senasoft-core-dev)
# ================================================

name: Build and deploy Node.js app to Azure Web App - senasoft-core-dev

on:
  push:
    branches:
      - main       # ⚡ Se dispara cada vez que hagas push en main
  workflow_dispatch: # ⚡ También puedes ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Requerido para checkout

    steps:
      # 1. Descarga el repo en el runner
      - uses: actions/checkout@v4

      # 2. Configura Node.js en la versión 22.x
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3. Instala dependencias y corre build/test
      # working-directory asegura que lo haga dentro de backend/core/nodejs
      - name: npm install, build, and test
        working-directory: ./backend/core/nodejs
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # 4. Sube el contenido de esa carpeta como artefacto
      # (esto es lo que se usará en el job de deploy)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend/core/nodejs/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # Requerido para OIDC con Azure
      contents: read  # Requerido para checkout

    steps:
      # 5. Descarga el artefacto del job anterior
      # Lo colocamos en ./app
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./app
      
      # 6. Login en Azure usando credenciales guardadas en Secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BA817C1F0B114A50BC105F4D8ED4FB7E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D27D600DBB694F00AE8CA456B1272AF4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2F036311BF4E4140862D335A33404959 }}

      # 7. Despliega el artefacto descargado (./app) al App Service
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'senasoft-core-dev'   # Nombre exacto del App Service
          slot-name: 'Production'         # Normalmente "Production"
          package: ./app                  # Aquí está el package.json y server.js
